// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
)

type RefreshToken struct {
	ID      uint32 `json:"id"`
	UserID  uint32 `json:"userId"`
	Token   string `json:"token"`
	Revoked bool   `json:"revoked"`
}

type Team struct {
	ID   uint32 `json:"id"`
	Name string `json:"name"`
}

type User struct {
	ID                uint32         `json:"id"`
	Email             string         `json:"email"`
	FirstName         string         `json:"firstName"`
	LastName          string         `json:"lastName"`
	MsftHomeAccountID sql.NullString `json:"msftHomeAccountId"`
}

type UserToTeam struct {
	UserID uint32 `json:"userId"`
	TeamID uint32 `json:"teamId"`
}
