name: Run Go Linting And Tests

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          submodules: "true"

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"

      - name: Set Up Make
        run: |
          sudo apt-get update
          sudo apt-get install -y make

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Run Lint
        run: make lint

      - name: Run Tests
        run: make test
